version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./pdf:/var/www/html/pdf
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - php
    networks:
      - app-network
  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
      - ./pdf:/var/www/html/pdf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  
  dockersock:
    image: websocket:latest
    container_name: dockersock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:2735
    networks:
      - app-network

networks:
    app-network:
      driver: bridge
